services:

  front-end:
    build: /vue_frontend
    ports:
      - "80:80"

  print_data_client:
    build: /printer_client
    ports:
      - "4000:4000"

  cloud_service_intake_process:
    build: /cloudservice_subscriber
    ports:
      - "3999:3999"

volumes:
  mongodb_data: